import { useState } from 'react'
import { Link, useNavigate, useOutletContext, useParams } from 'react-router-dom'
import { paths, roles } from '@/app/routes'
import { Alert } from '@/components/feedback/Alert'
import { EmptyState } from '@/components/feedback/EmptyState'
import { ErrorState } from '@/components/feedback/ErrorState'
import { LoadingState } from '@/components/feedback/LoadingState'
import { RouteAlert } from '@/components/feedback/RouteAlert'
import { PageContainer } from '@/components/layout/PageContainer'
import { PageHeader } from '@/components/layout/PageHeader'
import { RoleGate } from '@/components/routing/RoleGate'
import { ConfirmDialog } from '@/components/ui/ConfirmDialog'
import { ContentCard } from '@/components/ui/ContentCard'
import { DetailGrid } from '@/components/ui/DetailGrid'
import { ListToolbar } from '@/components/ui/ListToolbar'
import { Pagination } from '@/components/ui/Pagination'
import { ResponsiveTable } from '@/components/ui/ResponsiveTable'
import { SortableHeader } from '@/components/ui/SortableHeader'
import { FinanceRecordForm } from '@/features/finance/components/FinanceRecordForm'
import { useCreateExpense, useCreateTransaction, useDeleteExpense, useDeleteTransaction, useExpense, useExpenses, useFinanceSummary, useTransaction, useTransactions, useUpdateExpense, useUpdateTransaction } from '@/features/finance/hooks/financeQueries'
import { ForbiddenPage } from '@/pages/ForbiddenPage'
import { NotFoundPage } from '@/pages/NotFoundPage'
import { formatDateTime, formatNumber } from '@/utils/formatters'

const initialList = { page: 1, per_page: 15, search: '', sort: 'id', direction: 'desc' }
const toInputDate = (value) => value ? String(value).slice(0, 16) : ''

function FinanceCard({ color, label, value }) { return <div className="col-md"><div className={`info-box bg-${color}`}><div className="info-box-content"><span className="info-box-text">{label}</span><span className="info-box-number">{formatNumber(value)}</span></div></div></div> }

export function FinancePage() {
  const { user } = useOutletContext(); const [tab, setTab] = useState('transactions'); const [transactionParams, setTransactionParams] = useState(initialList); const [expenseParams, setExpenseParams] = useState(initialList); const [selected, setSelected] = useState(null)
  const summary = useFinanceSummary(); const transactions = useTransactions(transactionParams); const expenses = useExpenses(expenseParams); const deleteTransaction = useDeleteTransaction(); const deleteExpense = useDeleteExpense()
  const forbidden = [summary.error, transactions.error, expenses.error].some((error) => error?.status === 403); if (forbidden) return <ForbiddenPage />
  const activeParams = tab === 'transactions' ? transactionParams : expenseParams; const setActiveParams = tab === 'transactions' ? setTransactionParams : setExpenseParams; const activeQuery = tab === 'transactions' ? transactions : expenses
  function update(changes, resetPage = true) { setActiveParams((current) => ({ ...current, ...changes, ...(resetPage ? { page: 1 } : {}) })) }
  function sort(field) { setActiveParams((current) => ({ ...current, page: 1, sort: field, direction: current.sort === field && current.direction === 'asc' ? 'desc' : 'asc' })) }
  function confirmDelete() { const mutation = selected.kind === 'transaction' ? deleteTransaction : deleteExpense; mutation.mutate(selected.record.id, { onSuccess: () => setSelected(null) }) }
  const deleteError = deleteTransaction.error || deleteExpense.error
  return <><PageHeader title="حسابات مالی" /><section className="content"><PageContainer><RouteAlert />{deleteError ? <Alert variant="error">{deleteError.message}</Alert> : null}{summary.isPending ? <LoadingState /> : null}{summary.isError ? <ErrorState error={summary.error} onRetry={summary.refetch} /> : null}{summary.data ? <><div className="row"><FinanceCard color="info" label="تعداد تراکنش‌ها" value={summary.data.transaction_count} /><FinanceCard color="success" label="جمع درآمدها" value={summary.data.transaction_total} /><FinanceCard color="warning" label="تعداد هزینه‌ها" value={summary.data.expense_count} /><FinanceCard color="danger" label="جمع هزینه‌ها" value={summary.data.expense_total} /></div><ContentCard><div className="finance-balance"><div><h2>مانده خالص</h2><strong>{formatNumber(summary.data.net_balance)}</strong></div><RoleGate user={user} allowedRoles={[roles.admin]}><div className="form-actions"><Link className="btn btn-info" to={paths.transactionNew}>افزودن تراکنش جدید</Link><Link className="btn btn-success" to={paths.expenseNew}>افزودن هزینه جدید</Link></div></RoleGate></div></ContentCard></> : null}<ContentCard><div className="finance-tabs"><button type="button" className={`btn ${tab === 'transactions' ? 'btn-info' : 'btn-secondary'}`} onClick={() => setTab('transactions')}>تراکنش‌ها</button><button type="button" className={`btn ${tab === 'expenses' ? 'btn-info' : 'btn-secondary'}`} onClick={() => setTab('expenses')}>هزینه‌ها</button></div><ListToolbar search={activeParams.search} onSearch={(search) => update({ search })} perPage={activeParams.per_page} onPerPage={(per_page) => update({ per_page })} />{activeQuery.isPending ? <LoadingState /> : null}{activeQuery.isError ? <ErrorState error={activeQuery.error} onRetry={activeQuery.refetch} /> : null}{activeQuery.data ? <>{tab === 'transactions' ? <TransactionTable rows={activeQuery.data.data || []} params={activeParams} onSort={sort} user={user} onDelete={(record) => setSelected({ kind: 'transaction', record })} /> : <ExpenseTable rows={activeQuery.data.data || []} params={activeParams} onSort={sort} user={user} onDelete={(record) => setSelected({ kind: 'expense', record })} />}<Pagination meta={activeQuery.data.meta} onPageChange={(page) => update({ page }, false)} /></> : null}</ContentCard></PageContainer></section><ConfirmDialog open={Boolean(selected)} title={selected?.kind === 'transaction' ? 'حذف تراکنش' : 'حذف هزینه'} message="آیا مطمئن هستید که می‌خواهید این رکورد را حذف کنید؟" onCancel={() => setSelected(null)} onConfirm={confirmDelete} pending={deleteTransaction.isPending || deleteExpense.isPending} /></>
}

function TransactionTable({ rows, params, onSort, user, onDelete }) { return <ResponsiveTable className="table-bordered table-striped"><thead><tr><SortableHeader field="id" activeField={params.sort} direction={params.direction} onSort={onSort}>شناسه</SortableHeader><SortableHeader field="type" activeField={params.sort} direction={params.direction} onSort={onSort}>نوع</SortableHeader><SortableHeader field="amount" activeField={params.sort} direction={params.direction} onSort={onSort}>مبلغ</SortableHeader><SortableHeader field="transaction_date" activeField={params.sort} direction={params.direction} onSort={onSort}>تاریخ</SortableHeader><th>توضیحات</th><th>عملیات</th></tr></thead><tbody>{rows.length ? rows.map((item) => <tr key={item.id}><td>{item.id}</td><td>{item.type}</td><td>{formatNumber(item.amount)}</td><td>{formatDateTime(item.transaction_date)}</td><td>{item.description || '-'}</td><td><Actions user={user} detail={paths.transaction(item.id)} edit={paths.transactionEdit(item.id)} onDelete={() => onDelete(item)} /></td></tr>) : <tr><td colSpan="6"><EmptyState title="تراکنشی یافت نشد" /></td></tr>}</tbody></ResponsiveTable> }
function ExpenseTable({ rows, params, onSort, user, onDelete }) { return <ResponsiveTable className="table-bordered table-striped"><thead><tr><SortableHeader field="id" activeField={params.sort} direction={params.direction} onSort={onSort}>شناسه</SortableHeader><SortableHeader field="title" activeField={params.sort} direction={params.direction} onSort={onSort}>عنوان</SortableHeader><SortableHeader field="amount" activeField={params.sort} direction={params.direction} onSort={onSort}>مبلغ</SortableHeader><SortableHeader field="expense_date" activeField={params.sort} direction={params.direction} onSort={onSort}>تاریخ</SortableHeader><th>توضیحات</th><th>عملیات</th></tr></thead><tbody>{rows.length ? rows.map((item) => <tr key={item.id}><td>{item.id}</td><td>{item.title}</td><td>{formatNumber(item.amount)}</td><td>{formatDateTime(item.expense_date)}</td><td>{item.description || '-'}</td><td><Actions user={user} detail={paths.expense(item.id)} edit={paths.expenseEdit(item.id)} onDelete={() => onDelete(item)} /></td></tr>) : <tr><td colSpan="6"><EmptyState title="هزینه‌ای یافت نشد" /></td></tr>}</tbody></ResponsiveTable> }
function Actions({ user, detail, edit, onDelete }) { return <div className="btn-group table-actions"><Link className="btn btn-info" to={detail}><i className="fa-regular fa-eye" /></Link><RoleGate user={user} allowedRoles={[roles.admin]}><Link className="btn btn-warning" to={edit}><i className="fa-regular fa-pen-to-square" /></Link><button type="button" className="btn btn-danger" onClick={onDelete}><i className="fa-solid fa-trash-can" /></button></RoleGate></div> }

function RecordCreatePage({ kind }) { const navigate = useNavigate(); const transactionMutation = useCreateTransaction(); const expenseMutation = useCreateExpense(); const mutation = kind === 'transaction' ? transactionMutation : expenseMutation; const dateField = kind === 'transaction' ? 'transaction_date' : 'expense_date'; const titleField = kind === 'transaction' ? 'type' : 'title'; const initial = { [titleField]: '', amount: '', [dateField]: '', description: '' }; return <><PageHeader title={kind === 'transaction' ? 'تراکنش جدید' : 'هزینه جدید'} breadcrumbs={[{ label: 'حسابات مالی', to: paths.finance }]} /><section className="content"><PageContainer><article className="card card-info"><div className="card-header"><h2 className="card-title">فرم {kind === 'transaction' ? 'تراکنش' : 'هزینه'} جدید</h2></div><FinanceRecordForm kind={kind} initialValues={initial} onSubmit={(payload) => mutation.mutate(payload, { onSuccess: () => navigate(paths.finance, { state: { message: 'اطلاعات با موفقیت ثبت شد.' } }) })} pending={mutation.isPending} error={mutation.error} cancelTo={paths.finance} submitLabel="ذخیره" /></article></PageContainer></section></> }
export function TransactionCreatePage() { return <RecordCreatePage kind="transaction" /> }
export function ExpenseCreatePage() { return <RecordCreatePage kind="expense" /> }

function RecordDetailPage({ kind }) { const params = useParams(); const id = kind === 'transaction' ? params.transactionId : params.expenseId; const transaction = useTransaction(kind === 'transaction' ? id : null); const expense = useExpense(kind === 'expense' ? id : null); const query = kind === 'transaction' ? transaction : expense; if (query.error?.status === 404) return <NotFoundPage />; if (query.error?.status === 403) return <ForbiddenPage />; const item = query.data; return <><PageHeader title={kind === 'transaction' ? 'نمایش تراکنش' : 'نمایش هزینه'} breadcrumbs={[{ label: 'حسابات مالی', to: paths.finance }]} /><section className="content"><PageContainer>{query.isPending ? <LoadingState /> : null}{query.isError ? <ErrorState error={query.error} onRetry={query.refetch} /> : null}{item ? <ContentCard title="جزئیات"><DetailGrid items={[{ label: 'شناسه', value: item.id }, { label: kind === 'transaction' ? 'نوع' : 'عنوان', value: kind === 'transaction' ? item.type : item.title }, { label: 'مبلغ', value: formatNumber(item.amount) }, { label: 'تاریخ', value: formatDateTime(kind === 'transaction' ? item.transaction_date : item.expense_date) }, { label: 'توضیحات', value: item.description }]} /><div className="form-actions"><Link className="btn btn-secondary" to={paths.finance}>بازگشت</Link></div></ContentCard> : null}</PageContainer></section></> }
export function TransactionDetailPage() { return <RecordDetailPage kind="transaction" /> }
export function ExpenseDetailPage() { return <RecordDetailPage kind="expense" /> }

function RecordEditForm({ kind, item, mutation, onSuccess }) { const dateField = kind === 'transaction' ? 'transaction_date' : 'expense_date'; const titleField = kind === 'transaction' ? 'type' : 'title'; const initial = { [titleField]: item[titleField], amount: item.amount, [dateField]: toInputDate(item[dateField]), description: item.description || '' }; return <FinanceRecordForm kind={kind} initialValues={initial} onSubmit={(payload) => mutation.mutate({ id: item.id, payload }, { onSuccess })} pending={mutation.isPending} error={mutation.error} cancelTo={paths.finance} submitLabel="به‌روزرسانی" /> }
function RecordEditPage({ kind }) { const params = useParams(); const navigate = useNavigate(); const id = kind === 'transaction' ? params.transactionId : params.expenseId; const transaction = useTransaction(kind === 'transaction' ? id : null); const expense = useExpense(kind === 'expense' ? id : null); const transactionMutation = useUpdateTransaction(); const expenseMutation = useUpdateExpense(); const query = kind === 'transaction' ? transaction : expense; const mutation = kind === 'transaction' ? transactionMutation : expenseMutation; if (query.error?.status === 404) return <NotFoundPage />; if (query.error?.status === 403) return <ForbiddenPage />; return <><PageHeader title={kind === 'transaction' ? 'ویرایش تراکنش' : 'ویرایش هزینه'} breadcrumbs={[{ label: 'حسابات مالی', to: paths.finance }]} /><section className="content"><PageContainer><article className="card card-info"><div className="card-header"><h2 className="card-title">فرم ویرایش</h2></div>{query.isPending ? <LoadingState /> : null}{query.isError ? <ErrorState error={query.error} onRetry={query.refetch} /> : null}{query.data ? <RecordEditForm kind={kind} item={query.data} mutation={mutation} onSuccess={() => navigate(paths.finance, { state: { message: 'اطلاعات با موفقیت به‌روزرسانی شد.' } })} /> : null}</article></PageContainer></section></> }
export function TransactionEditPage() { return <RecordEditPage kind="transaction" /> }
export function ExpenseEditPage() { return <RecordEditPage kind="expense" /> }
